data:
  path: "data"
  competition: "rsna-2024-lumbar-spine-degenerative-classification"
  batch_size: 8
  num_workers: 4
  valid_ratio: 0.2
  view_type: Sagittal T2/STIR
  train_path: train_images
  test_path: test_images
  used_portion: 1 #1 to use the whole dataset, 0.1 to use 10%

optim:
  algo: SGD
  params:
    lr: 0.0001

nepochs: 20
loss: "CrossEntropyLoss"

logging:
  wandb:
    project: lumbar-spine
    entity: kaggle_coscoy
  log_file: "logs/app.log"
  log_level: INFO
  logdir: logs
# model:
#   class: Linear
model:
  class: VanillaCNN
  num_layers: 3
