data:
  path: "data"
  competition: "rsna-2024-lumbar-spine-degenerative-classification"
  # testpath: '/dummy/path/to/test'
  batch_size: 4
  num_workers: 4
  valid_ratio: 0.2
  view_type: Sagittal T2/STIR
  train_path: train_images
  test_path: test_images

optim:
  algo: SGD
  params:
    lr: 0.01

nepochs: 20
loss: "CrossEntropyLoss"

logging:
  # wandb:
  #   project: sample_project
  #   entity: sample_entity
  log_file: "logs/app.log"
  log_level: DEBUG
  logdir: logs
# model:
#   class: Linear
model:
  class: VanillaCNN
  num_layers: 4
